flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- cpphs-1.20.1
- ghcjs-dom-0.2.3.1
- haskell-src-exts-1.16.0.1
- ref-tf-0.4
- reflex-0.4.0
- reflex-dom-0.3
- syb-0.5.1
- webkitgtk3-0.14.1.1
- webkitgtk3-javascriptcore-0.13.1.2
resolver: lts-5.13
